//= require 'bower_components/jquery/dist/jquery.min.js'
//= require 'bower_components/qunit/qunit/qunit'
//= require 'bower_components/lodash/lodash.min.js'
//= require 'bower_components/modernizr/modernizr'

//= require 'src/qunit/kafe'
//= require 'src/qunit/date'
//= **require 'src/qunit/form'             // manual
//= **require 'src/qunit/geolocation'      // difficult to automate
//= require 'src/qunit/number'
//= require 'src/qunit/storage'
//= require 'src/qunit/string'
//= require 'src/qunit/string-encrypt'
//= require 'src/qunit/string-validate'
//= **require 'src/qunit/style'            // manual
//= require 'src/qunit/url'
//= **require 'src/qunit/cms/drupal'
//= **require 'src/qunit/cms/magento'
//= **require 'src/qunit/cms/sitecore'     // manual
//= **require 'src/qunit/ext/addthis'
//= **require 'src/qunit/ext/bbq'
//= **require 'src/qunit/ext/colorbox'
//= **require 'src/qunit/ext/disqus'
//= **require 'src/qunit/ext/facebook'
//= **require 'src/qunit/ext/flickr'
//= **require 'src/qunit/ext/googlemaps'
//= **require 'src/qunit/ext/soundcloud'
//= **require 'src/qunit/ext/twitter'
//= **require 'src/qunit/ext/youtube'
//= **require 'src/qunit/plugin/carousel'  // manual
//= **require 'src/qunit/plugin/menu'      // manual
//= **require 'src/qunit/plugin/qrcode'    // manual
//= **require 'src/qunit/plugin/sticky'    // manual

