// @import 'kafe'
// @import 'date'               // 2 methods pending
// **@import 'form'
// **@import 'geolocation'      // difficult to automate
// @import 'number'
// @import 'storage'
// @import 'string'
// @import 'string-encrypt'
// @import 'string-validate'
// **@import 'style'
// @import 'url'
// **@import 'cms/drupal'
// **@import 'cms/magento'
// **@import 'cms/sitecore'
// **@import 'ext/addthis'
// **@import 'ext/bbq'
// **@import 'ext/colorbox'
// **@import 'ext/disqus'
// **@import 'ext/facebook'
// **@import 'ext/flickr'
// **@import 'ext/googlemaps'
// **@import 'ext/soundcloud'
// **@import 'ext/twitter'
// **@import 'ext/youtube'
// **@import 'plugin/carousel'
// **@import 'plugin/menu'
// **@import 'plugin/qrcode'
// **@import 'plugin/sticky'